name: ✨ Feature Request
description: Suggest a new feature or enhancement for the OCR system
title: "[FEATURE] "
labels: ["enhancement", "needs-discussion"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please fill out the information below to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: 🎯 Problem Description
      description: Is your feature request related to a problem? Please describe.
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 💡 Proposed Solution
      description: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 🔄 Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: A clear and concise description of any alternative solutions or features you've considered.

  - type: dropdown
    id: feature-type
    attributes:
      label: 🏷️ Feature Type
      description: What type of feature is this?
      options:
        - New document classification
        - OCR engine improvement
        - Performance optimization
        - User interface enhancement
        - API enhancement
        - Configuration option
        - Integration with external service
        - Developer tooling
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: ⚡ Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve workflow
        - High - Critical for my use case
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: 📋 Use Case
      description: Describe your specific use case for this feature
      placeholder: |
        - What documents would this help with?
        - How would this improve your workflow?
        - What business value would this provide?
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: 🛠️ Implementation Ideas
      description: If you have ideas on how this could be implemented, please share them
      placeholder: Any technical ideas, API designs, or implementation approaches you have in mind

  - type: textarea
    id: additional-context
    attributes:
      label: 📝 Additional Context
      description: Add any other context, screenshots, or examples about the feature request here
